name: project
services:
  nginx:
    image: "nginx:1.27.2"
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf:/etc/nginx/conf.d

  flask:
    build: .
    volumes:
    - ./app:/app
    deploy: 
      replicas: 5
    command: flask --app main run --host=0.0.0.0
